all:
	git config --global user.name "Lorenzo Cabrini"
	git config --global user.email "lorenzo.cabrini@gmail.com"
	git config --global pull.ff only
	git config --global merge.ff false
	git config --global pull.rebase true
