#! /bin/sh

# Openbox autostart.
# Author: Lorenzo Cabrini <lorenzo.cabrini@gmail.com>

# I want this by default.
setxkbmap us &

# Random wallpaper.
feh --randomize --bg-fill ~/img/wp

# Start the compositor, if one is installed.
if [ -n "`command -v picom`" ]; then
    picom &
elif [ -n "`command -v compton`" ]; then
    compton &
fi

# Start conky.
conky &

# xscreensaver -nosplash &
